name: Build & Push Backend

on:
  push:
    branches: [main]
    paths:
      - "backend/**"
      - ".github/workflows/build-backend.yml"
  workflow_dispatch:

env:
  OCIR_REGISTRY: gru.ocir.io
  OCIR_NAMESPACE: grhkdi3glvat
  IMAGE_NAME: equipe-sudo/equipe-sudo-backend

jobs:
  build-and-push:
    name: Build & Push Backend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login OCIR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.OCIR_REGISTRY }}
          username: ${{ secrets.OCIR_USERNAME }}
          password: ${{ secrets.OCIR_AUTH_TOKEN }}

      - name: Build & Push
        uses: docker/build-push-action@v6
        with:
          context: backend
          push: true
          platforms: linux/arm64
          tags: |
            ${{ env.OCIR_REGISTRY }}/${{ env.OCIR_NAMESPACE }}/${{ env.IMAGE_NAME }}:latest
            ${{ env.OCIR_REGISTRY }}/${{ env.OCIR_NAMESPACE }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
